
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="ka">
<head>
<meta charset="UTF-8">
</head>

<head>
   

  

<link rel="stylesheet" type="text/css" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css">
<script type="text/javascript" src="http://caucasusoffline.com/datatable/tab1/tbc1.js"></script>
 <link rel="stylesheet" type="text/css" href="http://caucasusoffline.com/datatable/tab1/tbc1.css">
<script type="text/javascript" src="http://caucasusoffline.com/datatable/tab1/tbc3.js"></script>
</head>
  
</script>













<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{font-family:Arial, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
.tg th{font-family:Arial, sans-serif;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
.tg .tg-rtn9{font-size:xx-small;background-color:#3be6c4}
.tg .tg-86u9{font-size:xx-small;background-color:#33b7e2;vertical-align:top}
.tg .tg-rz1a{font-size:xx-small;background-color:#fd6864}
.tg .tg-sapl{font-size:xx-small}
.tg .tg-ihz4{font-size:xx-small;vertical-align:top}
.tg .tg-g54r{font-size:xx-small;background-color:#fd6864;vertical-align:top}
.tg .tg-pf0u{font-size:xx-small;background-color:#3be6c4;vertical-align:top}
</style>


<script type="text/javascript">
$(document).ready( function() {
	var static = true;
	var table = $("#dataTable-dsl").dataTable( {
		
		"language" : {
			"lengthMenu" : "Records per page _MENU_",
			"info" : "Page _PAGE_ of _PAGES_",
			"infoEmpty" : "No records available",
			"infoFiltered" : ""
			
		},
     
    iDisplayLength: 100,
		scrollY : 600,
		scrollX : static,	
	    "Sorting":['desc'],
		"dataSrc" : "data"
       
	});
 
	if(static)
		new $.fn.dataTable.FixedColumns( table, {
        leftColumns: 2,
        rightColumns: 2
    } );
} );
</script>




<table class="tg"  id="dataTable-dsl" style="undefined;table-layout: fixed; width: 1800px">
<thead>
  <tr>
    <th class="tg-rtn9">#</th>
    <th class="tg-rz1a"></th>
    <th class="tg-sapl">სილქნეტი</th>
    <th class="tg-ihz4">კავკასუსი /მაგთიკომი</th>
    <th class="tg-ihz4">ახალი ქსელები</th>
    <th class="tg-ihz4">ა-ნეტი</th>
    <th class="tg-ihz4">დელტა-ნეტი</th>
    <th class="tg-ihz4">სი-ჯი-სი</th>
    <th class="tg-ihz4">Xnet</th>
    <th class="tg-ihz4">ახტელი</th>
    <th class="tg-ihz4">ელიავა-ტექი</th>
    <th class="tg-ihz4">მაქსტელკომი - (404499253)</th>
    <th class="tg-ihz4">ფრინეტი</th>
    <th class="tg-ihz4">ორდუნეტ</th>
    <th class="tg-ihz4">G-Connect</th>
    <th class="tg-ihz4">გრიინეტი Ltd Greenet</th>
    <th class="tg-ihz4">გრენა</th>
    <th class="tg-ihz4">ლუკნეტ (LukNet)</th>
    <th class="tg-ihz4">რკინიგზის ტელეკომი</th>
    <th class="tg-ihz4">აილინკ</th>
    <th class="tg-ihz4">ინტეროპტიკა</th>
    <th class="tg-ihz4">ვი-ჯი-ეს ნეთვორქ</th>
    <th class="tg-ihz4">სისტემ ნეტ</th>
    <th class="tg-ihz4">სმარტნეტი</th>
    <th class="tg-ihz4">გლობალკომი</th>
    <th class="tg-ihz4">SKY FI</th>
    <th class="tg-ihz4">დელტა კომმი</th>
    <th class="tg-ihz4">სერვისნეტ</th>
    <th class="tg-ihz4">ტვ ნეტ</th>
    <th class="tg-ihz4">სქაიტელი</th>
    <th class="tg-ihz4">აირმაქსი</th>
    <th class="tg-ihz4">ენჯი სისტემსი</th>
    <th class="tg-ihz4">ისტერა</th>
    <th class="tg-ihz4">პელიკომი</th>
    <th class="tg-g54r">ჯამი / Total</th>
    <th class="tg-g54r">Total %</th>
  </tr>
   </thead>
  <tr>
    <td class="tg-pf0u">1</td>
    <td class="tg-g54r">ქ. თბილისი</td>
    <td class="tg-ihz4">7763</td>
    <td class="tg-ihz4">5805</td>
    <td class="tg-ihz4">485</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4">534</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4">431</td>
    <td class="tg-ihz4">327</td>
    <td class="tg-ihz4">160</td>
    <td class="tg-ihz4">136</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4">25</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4">15</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4">3</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4">8</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4">4</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4">2</td>
    <td class="tg-ihz4">2</td>
    <td class="tg-ihz4">2</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4">1</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4">1</td>
    <td class="tg-ihz4">1</td>
    <td class="tg-ihz4">1</td>
    <td class="tg-g54r">15706</td>
    <td class="tg-g54r">78,593%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">2</td>
    <td class="tg-g54r">ქ. ბათუმი</td>
    <td class="tg-ihz4">427</td>
    <td class="tg-ihz4">330</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4">1039</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4">2</td>
    <td class="tg-ihz4">21</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">1819</td>
    <td class="tg-g54r">9,102%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">3</td>
    <td class="tg-g54r">ქ. ქუთაისი</td>
    <td class="tg-ihz4">134</td>
    <td class="tg-ihz4">19</td>
    <td class="tg-ihz4">558</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4">2</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">713</td>
    <td class="tg-g54r">3,568%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">4</td>
    <td class="tg-g54r">ქ. რუსთავი</td>
    <td class="tg-ihz4">16</td>
    <td class="tg-ihz4">60</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4">418</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4">1</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">495</td>
    <td class="tg-g54r">2,477%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">5</td>
    <td class="tg-g54r">ქ. ფოთი</td>
    <td class="tg-ihz4">62</td>
    <td class="tg-ihz4">117</td>
    <td class="tg-ihz4">124</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4">2</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4">1</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">306</td>
    <td class="tg-g54r">1,531%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">6</td>
    <td class="tg-g54r">ქ. ზუგდიდი</td>
    <td class="tg-ihz4">20</td>
    <td class="tg-ihz4">103</td>
    <td class="tg-ihz4">42</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4">45</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">210</td>
    <td class="tg-g54r">1,051%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">7</td>
    <td class="tg-g54r">ქ. გორი</td>
    <td class="tg-ihz4">13</td>
    <td class="tg-ihz4">4</td>
    <td class="tg-ihz4">107</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4">2</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4">3</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">129</td>
    <td class="tg-g54r">0,646%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">8</td>
    <td class="tg-g54r">ქ. თელავი</td>
    <td class="tg-ihz4">68</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4">49</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">117</td>
    <td class="tg-g54r">0,585%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">9</td>
    <td class="tg-g54r">ქ. ზესტაფონი</td>
    <td class="tg-ihz4">8</td>
    <td class="tg-ihz4">1</td>
    <td class="tg-ihz4">88</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">97</td>
    <td class="tg-g54r">0,485%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">10</td>
    <td class="tg-g54r">ქ. ქობულეთი</td>
    <td class="tg-ihz4">7</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4">76</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">83</td>
    <td class="tg-g54r">0,415%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">11</td>
    <td class="tg-g54r">ქ. გარდაბანი</td>
    <td class="tg-ihz4">5</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4">55</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">60</td>
    <td class="tg-g54r">0,300%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">12</td>
    <td class="tg-g54r">ქ. გურჯაანი</td>
    <td class="tg-ihz4">52</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">52</td>
    <td class="tg-g54r">0,260%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">13</td>
    <td class="tg-g54r">დაბა ჩოხატაური</td>
    <td class="tg-ihz4">25</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">25</td>
    <td class="tg-g54r">0,125%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">14</td>
    <td class="tg-g54r">ქ. სამტრედია</td>
    <td class="tg-ihz4">3</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4">9</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4">6</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">18</td>
    <td class="tg-g54r">0,090%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">15</td>
    <td class="tg-g54r">ქ. მარნეული</td>
    <td class="tg-ihz4">7</td>
    <td class="tg-ihz4">1</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4">9</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">17</td>
    <td class="tg-g54r">0,085%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">16</td>
    <td class="tg-g54r">ქ. ბორჯომი</td>
    <td class="tg-ihz4">14</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">14</td>
    <td class="tg-g54r">0,070%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">17</td>
    <td class="tg-g54r">ქ. ხაშური</td>
    <td class="tg-ihz4">11</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">11</td>
    <td class="tg-g54r">0,055%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">18</td>
    <td class="tg-g54r">ქ. ჭიათურა</td>
    <td class="tg-ihz4">3</td>
    <td class="tg-ihz4">1</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4">3</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4">2</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">9</td>
    <td class="tg-g54r">0,045%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">19</td>
    <td class="tg-g54r">ქ. სიღნაღი</td>
    <td class="tg-ihz4">8</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">8</td>
    <td class="tg-g54r">0,040%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">20</td>
    <td class="tg-g54r">ქ. ოზურგეთი</td>
    <td class="tg-ihz4">4</td>
    <td class="tg-ihz4">4</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">8</td>
    <td class="tg-g54r">0,040%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">21</td>
    <td class="tg-g54r">ქ. ბოლნისი</td>
    <td class="tg-ihz4">6</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4">1</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">7</td>
    <td class="tg-g54r">0,035%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">22</td>
    <td class="tg-g54r">დაბა სტეფანწმინდა</td>
    <td class="tg-ihz4">7</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">7</td>
    <td class="tg-g54r">0,035%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">23</td>
    <td class="tg-g54r">ქ. დედოფლისწყარო</td>
    <td class="tg-ihz4">6</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">6</td>
    <td class="tg-g54r">0,030%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">24</td>
    <td class="tg-g54r">ქ. ახალციხე</td>
    <td class="tg-ihz4">6</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">6</td>
    <td class="tg-g54r">0,030%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">25</td>
    <td class="tg-g54r">ქ. წყალტუბო</td>
    <td class="tg-ihz4">5</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">5</td>
    <td class="tg-g54r">0,025%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">26</td>
    <td class="tg-g54r">ქ. დუშეთი</td>
    <td class="tg-ihz4">3</td>
    <td class="tg-ihz4">1</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4">1</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">5</td>
    <td class="tg-g54r">0,025%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">27</td>
    <td class="tg-g54r">ქ. ბაღდათი</td>
    <td class="tg-ihz4">3</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4">2</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">5</td>
    <td class="tg-g54r">0,025%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">28</td>
    <td class="tg-g54r">ქ. საჩხერე</td>
    <td class="tg-ihz4">1</td>
    <td class="tg-ihz4">3</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4">1</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">5</td>
    <td class="tg-g54r">0,025%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">29</td>
    <td class="tg-g54r">ქ. სენაკი</td>
    <td class="tg-ihz4">3</td>
    <td class="tg-ihz4">1</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">4</td>
    <td class="tg-g54r">0,020%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">30</td>
    <td class="tg-g54r">ქ. კასპი</td>
    <td class="tg-ihz4">2</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4">2</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">4</td>
    <td class="tg-g54r">0,020%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">31</td>
    <td class="tg-g54r">ქ. ხობი</td>
    <td class="tg-ihz4">3</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">3</td>
    <td class="tg-g54r">0,015%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">32</td>
    <td class="tg-g54r">ქ. მცხეთა</td>
    <td class="tg-ihz4">3</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">3</td>
    <td class="tg-g54r">0,015%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">33</td>
    <td class="tg-g54r">ქ. ახალქალაქი</td>
    <td class="tg-ihz4">3</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">3</td>
    <td class="tg-g54r">0,015%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">34</td>
    <td class="tg-g54r">დაბა ასპინძა</td>
    <td class="tg-ihz4">3</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">3</td>
    <td class="tg-g54r">0,015%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">35</td>
    <td class="tg-g54r">ქ. ყვარელი</td>
    <td class="tg-ihz4">2</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">2</td>
    <td class="tg-g54r">0,010%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">36</td>
    <td class="tg-g54r">ქ. ტყიბული</td>
    <td class="tg-ihz4">2</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">2</td>
    <td class="tg-g54r">0,010%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">37</td>
    <td class="tg-g54r">ქ. თეთრი წყარო</td>
    <td class="tg-ihz4">2</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">2</td>
    <td class="tg-g54r">0,010%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">38</td>
    <td class="tg-g54r">ქ. აბაშა</td>
    <td class="tg-ihz4">2</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">2</td>
    <td class="tg-g54r">0,010%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">39</td>
    <td class="tg-g54r">დაბა ხარაგაული</td>
    <td class="tg-ihz4">2</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">2</td>
    <td class="tg-g54r">0,010%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">40</td>
    <td class="tg-g54r">დაბა ურეკი</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4">2</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">2</td>
    <td class="tg-g54r">0,010%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">41</td>
    <td class="tg-g54r">ქ. ხონი</td>
    <td class="tg-ihz4">1</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">1</td>
    <td class="tg-g54r">0,005%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">42</td>
    <td class="tg-g54r">ქ. წალკა</td>
    <td class="tg-ihz4">1</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">1</td>
    <td class="tg-g54r">0,005%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">43</td>
    <td class="tg-g54r">ქ. წალენჯიხა</td>
    <td class="tg-ihz4">1</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">1</td>
    <td class="tg-g54r">0,005%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">44</td>
    <td class="tg-g54r">ქ. მარტვილი</td>
    <td class="tg-ihz4">1</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">1</td>
    <td class="tg-g54r">0,005%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">45</td>
    <td class="tg-g54r">ქ. ლაგოდეხი</td>
    <td class="tg-ihz4">1</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">1</td>
    <td class="tg-g54r">0,005%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">46</td>
    <td class="tg-g54r">ქ. დმანისი</td>
    <td class="tg-ihz4">1</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">1</td>
    <td class="tg-g54r">0,005%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">47</td>
    <td class="tg-g54r">დაბა ხულო</td>
    <td class="tg-ihz4">1</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">1</td>
    <td class="tg-g54r">0,005%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">48</td>
    <td class="tg-g54r">დაბა ჩხოროწყუ</td>
    <td class="tg-ihz4">1</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">1</td>
    <td class="tg-g54r">0,005%</td>
  </tr>
  <tr>
    <td class="tg-pf0u">49</td>
    <td class="tg-g54r">დაბა ადიგენი</td>
    <td class="tg-ihz4">1</td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-ihz4"></td>
    <td class="tg-g54r">1</td>
    <td class="tg-g54r">0,005%</td>
  </tr>
   <tfoot>  
  <tr>
    <td class="tg-pf0u"></td>
    <td class="tg-pf0u">ჯამი / Total</td>
    <td class="tg-86u9">8 723</td>
    <td class="tg-86u9">6 450</td>
    <td class="tg-86u9">1 406</td>
    <td class="tg-86u9">1 115</td>
    <td class="tg-86u9">534</td>
    <td class="tg-86u9">473</td>
    <td class="tg-86u9">431</td>
    <td class="tg-86u9">327</td>
    <td class="tg-86u9">160</td>
    <td class="tg-86u9">136</td>
    <td class="tg-86u9">49</td>
    <td class="tg-86u9">45</td>
    <td class="tg-86u9">31</td>
    <td class="tg-86u9">21</td>
    <td class="tg-86u9">15</td>
    <td class="tg-86u9">9</td>
    <td class="tg-86u9">9</td>
    <td class="tg-86u9">9</td>
    <td class="tg-86u9">8</td>
    <td class="tg-86u9">6</td>
    <td class="tg-86u9">5</td>
    <td class="tg-86u9">3</td>
    <td class="tg-86u9">3</td>
    <td class="tg-86u9">2</td>
    <td class="tg-86u9">2</td>
    <td class="tg-86u9">2</td>
    <td class="tg-86u9">2</td>
    <td class="tg-86u9">2</td>
    <td class="tg-86u9">2</td>
    <td class="tg-86u9">2</td>
    <td class="tg-86u9">1</td>
    <td class="tg-86u9">1</td>
    <td class="tg-86u9">19 984</td>
    <td class="tg-86u9"></td>
  </tr>
  <tr>
    <td class="tg-pf0u"></td>
    <td class="tg-pf0u">Total %</td>
    <td class="tg-86u9">43,650%</td>
    <td class="tg-86u9">32,276%</td>
    <td class="tg-86u9">7,036%</td>
    <td class="tg-86u9">5,579%</td>
    <td class="tg-86u9">2,672%</td>
    <td class="tg-86u9">2,367%</td>
    <td class="tg-86u9">2,157%</td>
    <td class="tg-86u9">1,636%</td>
    <td class="tg-86u9">0,801%</td>
    <td class="tg-86u9">0,681%</td>
    <td class="tg-86u9">0,245%</td>
    <td class="tg-86u9">0,225%</td>
    <td class="tg-86u9">0,155%</td>
    <td class="tg-86u9">0,105%</td>
    <td class="tg-86u9">0,075%</td>
    <td class="tg-86u9">0,045%</td>
    <td class="tg-86u9">0,045%</td>
    <td class="tg-86u9">0,045%</td>
    <td class="tg-86u9">0,040%</td>
    <td class="tg-86u9">0,030%</td>
    <td class="tg-86u9">0,025%</td>
    <td class="tg-86u9">0,015%</td>
    <td class="tg-86u9">0,015%</td>
    <td class="tg-86u9">0,010%</td>
    <td class="tg-86u9">0,010%</td>
    <td class="tg-86u9">0,010%</td>
    <td class="tg-86u9">0,010%</td>
    <td class="tg-86u9">0,010%</td>
    <td class="tg-86u9">0,010%</td>
    <td class="tg-86u9">0,010%</td>
    <td class="tg-86u9">0,005%</td>
    <td class="tg-86u9">0,005%</td>
    <td class="tg-86u9"></td>
    <td class="tg-86u9"></td>
  </tr>

  </thead>
  
</table>
</body>
</html>